package com.tsystems.lection12.entities;

// Generated 25.11.2013 11:52:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "STUDENT", schema = "PUBLIC", catalog = "PUBLIC")
public class Student implements java.io.Serializable {

	private Integer id;
	private User user;
	private String studentNo;
	private Set<TeacherReview> teacherReviews = new HashSet<TeacherReview>(0);

	public Student() {
	}

	public Student(User user) {
		this.user = user;
	}

	public Student(User user, String studentNo,
			Set<TeacherReview> teacherReviews) {
		this.user = user;
		this.studentNo = studentNo;
		this.teacherReviews = teacherReviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "STUDENT_NO", length = 64)
	public String getStudentNo() {
		return this.studentNo;
	}

	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "student")
	public Set<TeacherReview> getTeacherReviews() {
		return this.teacherReviews;
	}

	public void setTeacherReviews(Set<TeacherReview> teacherReviews) {
		this.teacherReviews = teacherReviews;
	}

}
